name = "hono-file"
main = "src/index.ts"
compatibility_date = "2025-07-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
not_found_handling = "single-page-application"


[build]
command = "corepack enable && pnpm install --frozen-lockfile && pnpm run build"

[[d1_databases]]
binding = "DB"
database_name = "hono-file"
database_id = "32cfe7f8-e9fe-4265-95d1-f9e65d8ebd83"
migrations_dir = "drizzle"



[[r2_buckets]]
binding         = "FILE"
bucket_name     = "hono-file"