name = "hono_file"
main = "src/index.ts"
compatibility_date = "2025-07-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"

[build]
command = "corepack enable && pnpm install --frozen-lockfile && pnpm run build"
