name = "hono-file"
main = "src/index.ts"
compatibility_date = "2025-07-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
not_found_handling = "single-page-application"


[build]
command = "corepack enable && pnpm install --frozen-lockfile && pnpm run build"
